name: expense_tracker_lite
description: A production-grade Expense Tracker Lite Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # DI
  injectable: ^2.3.2
  get_it: ^7.6.4
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Networking
  dio: ^5.3.3
  
  # UI
  flutter_screenutil: ^5.9.0
  intl: ^0.20.2
  
  # Utils
  dartz: ^0.10.1
  uuid: ^4.2.1
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  flutter_svg: ^2.2.3
  file_picker: ^10.3.7
  fluttertoast: ^9.0.0
  device_preview: ^1.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.10.0
  hive_generator: ^2.0.1
  
  # Testing
  mocktail: ^1.0.0
  bloc_test: ^9.1.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-PRO-Bold.otf
          weight: 900
        - asset: assets/fonts/SF-PRO-Semibold.ttf
          weight: 700
        - asset: assets/fonts/SF-PRO-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-PRO-Regular.otf
          weight: 400
        
